name: Update Sony SAB Playlist

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-m3u:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run script
        run: python extract_sab.py

      - name: Save and commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: sony_sab_sd.m3u
          commit_message: "Auto-update Sony SAB M3U file"
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "actions@github.com"
